// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace AutoGenConfig
{

using global::System;
using global::FlatBuffers;

public struct Sheet1Config : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Sheet1Config GetRootAsSheet1Config(ByteBuffer _bb) { return GetRootAsSheet1Config(_bb, new Sheet1Config()); }
  public static Sheet1Config GetRootAsSheet1Config(ByteBuffer _bb, Sheet1Config obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool Sheet1ConfigBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "WHAT"); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Sheet1Config __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SingleSheet1ConfigData? Data(int j) { int o = __p.__offset(4); return o != 0 ? (SingleSheet1ConfigData?)(new SingleSheet1ConfigData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DataLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Sheet1Config> CreateSheet1Config(FlatBufferBuilder builder,
      VectorOffset dataOffset = default(VectorOffset)) {
    builder.StartObject(1);
    Sheet1Config.AddData(builder, dataOffset);
    return Sheet1Config.EndSheet1Config(builder);
  }

  public static void StartSheet1Config(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(0, dataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, Offset<SingleSheet1ConfigData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Sheet1Config> EndSheet1Config(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Sheet1Config>(o);
  }
  public static void FinishSheet1ConfigBuffer(FlatBufferBuilder builder, Offset<Sheet1Config> offset) { builder.Finish(offset.Value, "WHAT"); }
};

public struct SingleSheet1ConfigData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static SingleSheet1ConfigData GetRootAsSingleSheet1ConfigData(ByteBuffer _bb) { return GetRootAsSingleSheet1ConfigData(_bb, new SingleSheet1ConfigData()); }
  public static SingleSheet1ConfigData GetRootAsSingleSheet1ConfigData(ByteBuffer _bb, SingleSheet1ConfigData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public SingleSheet1ConfigData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Data1 { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetData1Bytes() { return __p.__vector_as_arraysegment(6); }
  public int Data2 { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<SingleSheet1ConfigData> CreateSingleSheet1ConfigData(FlatBufferBuilder builder,
      int ID = 0,
      StringOffset data1Offset = default(StringOffset),
      int data2 = 0) {
    builder.StartObject(3);
    SingleSheet1ConfigData.AddData2(builder, data2);
    SingleSheet1ConfigData.AddData1(builder, data1Offset);
    SingleSheet1ConfigData.AddID(builder, ID);
    return SingleSheet1ConfigData.EndSingleSheet1ConfigData(builder);
  }

  public static void StartSingleSheet1ConfigData(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddID(FlatBufferBuilder builder, int ID) { builder.AddInt(0, ID, 0); }
  public static void AddData1(FlatBufferBuilder builder, StringOffset data1Offset) { builder.AddOffset(1, data1Offset.Value, 0); }
  public static void AddData2(FlatBufferBuilder builder, int data2) { builder.AddInt(2, data2, 0); }
  public static Offset<SingleSheet1ConfigData> EndSingleSheet1ConfigData(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SingleSheet1ConfigData>(o);
  }
};


}
